//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by emule.rc
//
#define IDC_STATUSBAR                   100
#define IDD_EMULE_DIALOG                102
#define IDS_SOCKETS_INIT_FAILED         104
#define IDS_HTTPDOWNLOAD_FILESTATUS     106
#define IDS_HTTPDOWNLOAD_CONNECTED      107
#define IDS_HTTPDOWNLOAD_RESOLVING_NAME 108
#define IDS_HTTPDOWNLOAD_RESOLVED_NAME  109
#define IDS_HTTPDOWNLOAD_CONNECTING     110
#define IDS_HTTPDOWNLOAD_REDIRECTING    111
#define IDS_HTTPDOWNLOAD_GETTING_FILE_INFORMATION 112
#define IDS_HTTPDOWNLOAD_GENERIC_ERROR  113
#define IDS_HTTPDOWNLOAD_FAIL_CONNECT_SERVER 114
#define IDS_HTTPDOWNLOAD_INVALID_SERVER_RESPONSE 115
#define IDS_HTTPDOWNLOAD_INVALID_HTTP_RESPONSE 116
#define IDS_HTTPDOWNLOAD_ERROR_READFILE 117
#define IDS_HTTPDOWNLOAD_PERCENTAGE     118
#define IDS_HTTPDOWNLOAD_RETREIVEING_FILE 119
#define IDS_HTTPDOWNLOAD_OF             120
#define IDS_FILELINK                    121
#define IDS_LD_BASICOPT                 122
#define IDS_LD_ADDSOURCE                123
#define IDS_LD_EMULEHASH                124
#define IDS_LD_ADVANCEDOPT              125
#define IDS_CANCEL                      126
#define IDS_HTTP_CAPTION                128
#define IDS_HTTPDOWNLOAD_TIMELEFT       129
#define IDS_LD_ADDHASHSET               130
#define IDS_HSAV                        131
#define IDS_DL_SHOWED2KLINK             132
#define IDS_FD_CORR                     133
#define IDD_TRANSFER                    134
#define IDS_HTTPDOWNLOAD_OK_TO_OVERWRITE 134
#define IDS_FD_RECOV                    135
#define IDD_SERVER                      136
#define IDS_HTTPDOWNLOAD_FAIL_FILE_OPEN 136
#define IDS_HTTPDOWNLOAD_ABORTING_TRANSFER 137
#define IDS_FD_COMPR                    138
#define IDS_MAIN_READY                  140
#define IDD_SEARCH                      142
#define IDS_MAIN_SOCKETERROR            143
#define IDS_MAIN_BTN_DISCONNECT         144
#define IDS_ERR_WRONGFILEID             145
#define IDS_ERR_BADHASHSET              146
#define IDS_ERR_BADDATABLOCK            147
#define IDS_ERR_ILLFORMEDHASH           148
#define IDS_ERR_BADED2KLINK             149
#define IDS_ERR_NOSLLINK                150
#define IDS_ERR_WRONGPACKAGESIZE        151
#define IDS_ERR_WRONGHPACKAGESIZE       152
#define IDS_ERR_UNKNOWNCLIENTACTION     153
#define IDS_ERR_OPENMET                 154
#define IDS_ERR_BADMETVERSION           155
#define IDS_ERR_METCORRUPT              156
#define IDS_ERR_FILEERROR               157
#define IDS_ERR_FILEOPEN                158
#define IDS_ERR_REHASH                  160
#define IDS_ERR_PART_FNF                162
#define IDD_HTTPDOWNLOAD                163
#define IDS_KADOPEN                     163
#define IDS_ERR_SAVEMET                 164
#define IDS_ERR_FOUNDCORRUPTION         165
#define IDS_HASHINGDONE                 166
#define IDS_ERR_PARTCORRUPT             167
#define IDS_ICHWORKED                   168
#define IDS_ERR_OUTOFSPACE              169
#define IDS_SE                          170
#define IDS_ERR_WRITEERROR              171
#define IDS_ERR_COMPLETIONFAILED        172
#define IDS_ERR_DELETEFAILED            173
#define IDS_DOWNLOADDONE                174
#define IDD_SOURCEDETAILWND             175
#define IDS_ERR_DELETE                  175
#define IDS_ERR_HASHERRORWARNING        176
#define IDS_ERR_INCOMPLETEHASH          177
#define IDS_DOWNLOADING                 178
#define IDS_WAITING                     179
#define IDS_HASHING                     180
#define IDS_COMPLETING                  181
#define IDS_COMPLETE                    182
#define IDS_PAUSED                      183
#define IDS_ERRORLIKE                   184
#define IDS_ASSIGNED2K                  185
#define IDS_ERR_BADSERVERMETVERSION     187
#define IDS_SERVERSFOUND                188
#define IDS_SERVERSADDED                189
#define IDS_ERR_BADSERVERLIST           190
#define IDS_ERR_FILEERROR_SERVERMET     191
#define IDS_ERR_SAVESERVERMET           192
#define IDS_PASSIVE                     193
#define IDS_MAIN_BTN_CANCEL             194
#define IDS_AVAIL                       195
#define IDS_TYPE                        196
#define IDS_FILEID                      197
#define IDS_FILE                        198
#define IDS_DOWNLOAD                    199
#define IDS_SL_SERVERNAME               200
#define IDS_IP                          201
#define IDS_DESCRIPTION                 202
#define IDS_PING                        203
#define IDS_FILES                       204
#define IDS_PREFERENCE                  205
#define IDS_PRIONOPREF                  206
#define IDS_CONNECTTHIS                 207
#define IDS_MAIN_BTN_CONNECT            208
#define IDS_ERR_SAVESERVERMET2          209
#define IDS_NOTCONNECTED                210
#define IDS_DISCONNECTED                211
#define IDS_CONNECTED                   214
#define IDS_LINKNOTADDED                215
#define IDS_MAIN_EXIT                   216
#define IDS_MAIN_POPUP_RESTORE          217
#define IDS_CONNECTTOANYSERVER          218
#define IDS_EXIT                        219
#define IDS_CONNECTING                  220
#define IDS_ERR_BADSERVERREPLY          222
#define IDS_NEWCLIENTID                 223
#define IDS_PRIOLOW                     227
#define IDS_PRIONORMAL                  228
#define IDS_PRIOHIGH                    229
#define IDS_PRIORITY                    231
#define IDS_NEWSERVERS                  232
#define IDS_DL_STOP                     233
#define IDS_DL_PAUSE                    234
#define IDS_DL_RESUME                   235
#define IDS_DL_OPEN                     236
#define IDS_DL_INFO                     237
#define IDS_DL_LINK1                    239
#define IDS_SHOWDETAILS                 241
#define IDS_ASKING                      243
#define IDS_CONNVIASERVER               244
#define IDS_ONQUEUE                     245
#define IDS_TRANSFERRING                246
#define IDS_RECHASHSET                  247
#define IDS_NONEEDEDPARTS               248
#define IDS_NOCONNECTLOW2LOW            249
#define IDS_UNKNOWN                     250
#define IDS_ASKED4ANOTHERFILE           251
#define IDS_Q_CANCELDL                  252
#define IDS_Q_CANCELDL2                 253
#define IDS_DL_FILENAME                 254
#define IDS_DL_SIZE                     255
#define IDS_DL_TRANSF                   256
#define IDS_DL_SPEED                    257
#define IDS_DL_PROGRESS                 258
#define IDS_DL_SOURCES                  259
#define IDS_STATUS                      261
#define IDS_DL_REMAINS                  262
#define IDS_UPDATEFROM                  263
#define IDS_LOADURL                     265
#define IDS_DELETEAFTERALLOC            266
#define IDS_CONNECTINGTO                268
#define IDS_CLIENTS                     269
#define IDS_SEARCH_ANY                  270
#define IDS_SEARCH_AUDIO                271
#define IDS_SEARCH_PICS                 272
#define IDS_SEARCH_PRG                  273
#define IDS_SEARCH_VIDEO                274
#define IDS_SEARCH_CDIMG                275
#define IDS_SEARCH_ARC                  276
#define IDS_ERR_INVALIDLINK             277
#define IDB_UP                          278
#define IDS_ERR_LINKERROR               278
#define IDS_ERR_NOTCONNECTED            279
#define IDS_REMOVETHIS                  280
#define IDB_DOWN                        281
#define IDS_REMOVEALL                   281
#define IDS_SRV_ADDR                    282
#define IDS_SRV_PORT                    283
#define IDS_SRV_NOTADDED                284
#define IDS_INVALIDURL                  286
#define IDS_ERR_FAILEDDOWNLOADMET       287
#define IDS_PERMISSION                  288
#define IDS_SHAREDFILES                 289
#define IDS_PRIOVERYLOW                 290
#define IDS_PRIORELEASE                 291
#define IDS_VIAPASSIVE                  294
#define IDS_ERR_RENAMESF                295
#define IDS_AVAILABLE                   296
#define IDS_FSTAT_TRANSFER              297
#define IDS_FSTAT_CONNECTION            298
#define IDS_FSTAT_SERVERS               299
#define IDS_FSTAT_WAITING               300
#define IDS_TIME                        301
#define IDS_STATS_DDATA                 302
#define IDS_STATS_UDATA                 303
#define IDS_STATS_AVGDL                 304
#define IDS_STATS_AVGUL                 305
#define IDS_STATS_FOUNDSRC              306
#define IDS_STATS_ACTDL                 307
#define IDS_STATS_ACTUL                 308
#define IDD_PPG_CONNECTION              309
#define IDS_STATS_WAITINGUSERS          309
#define IDS_STATS_RECONNECTS            310
#define IDD_PPG_DIRECTORIES             311
#define IDS_STATS_TOTAL                 312
#define IDD_PPG_FILES                   313
#define IDS_DISABLED                    313
#define IDS_STOPPED                     314
#define IDD_PPG_GENERAL                 315
#define IDS_STATS_UPDATELABEL           315
#define IDS_ASKEDFAF                    316
#define IDS_WAITED                      317
#define IDS_ERR_LOADCREDITFILE          318
#define IDS_ERR_CREDITFILEOLD           319
#define IDS_CREDITFILELOADED            320
#define IDS_CREDITFILECORRUPT           321
#define IDS_ERR_CREDITFILEREAD          322
#define IDS_ERR_FAILED_CREDITSAVE       323
#define IDS_NOPARTSFOUND                324
#define IDS_FOUNDPARTS                  325
#define IDS_NEWDOWNLOAD                 326
#define IDS_ERR_ALREADY_DOWNLOADING     327
#define IDS_ERR_ALREADY_DOWNLOADED      328
#define IDS_ERR_SERVERMET_BAD           329
#define IDS_ERR_SERVERMET_UNKNOWN       330
#define IDS_ERR_CONNECTIONERROR         331
#define IDS_ERR_SOCKET                  332
#define IDS_SHAREDFOUND                 333
#define IDS_SHAREDFOUNDHASHING          334
#define IDS_ERR_INCOMPLETEBLOCK         335
#define IDS_ERR_OPEN                    336
#define IDS_ERR_CLIENTERRORED           337
#define IDS_ERR_REQ_FNF                 338
#define IDS_DESC                        339
#define IDS_PORT                        340
#define IDS_ERR_NOVALIDSERVERSFOUND     341
#define IDS_CONNECTEDTOREQ              342
#define IDS_ERR_FATAL                   343
#define IDS_ERR_LOSTC                   344
#define IDS_ERR_DEAD                    345
#define IDS_ERR_FULL                    346
#define IDS_CONNECTEDTO                 347
#define IDS_DL_PREVIEW                  348
#define IDS_TW_UPLOADS                  350
#define IDS_TW_DOWNLOADS                351
#define IDS_SW_NAME                     354
#define IDS_SW_GLOBAL                   355
#define IDS_SW_DIRECTDOWNLOAD           356
#define IDS_SW_LINK                     357
#define IDS_SW_START                    358
#define IDS_SW_RESULT                   361
#define IDS_SV_SERVERLIST               363
#define IDS_SV_LOG                      365
//#define IDS_SV_ADDRESS                  367
//#define IDS_SV_PORT                     368
#define IDS_SV_UPDATE                   371
#define IDS_SF_FILES                    372
#define IDS_SF_STATISTICS               373
#define IDS_SF_RELOAD                   374
#define IDS_SF_TRANS                    377
#define IDS_SF_REQUESTED                379
#define IDS_ST_DOWNLOAD                 380
#define IDS_ST_UPLOAD                   381
#define IDS_ST_CURRENT                  382
#define IDS_ST_SESSION                  383
#define IDS_ST_ACTIVEU                  385
#define IDS_PW_GENERAL                  390
#define IDS_PW_DIR                      391
//#define IDS_PW_NICK                     392
#define IDS_PW_INCOMING                 393
#define IDS_PW_TEMP                     394
#define IDS_PW_SHARED                   396
#define IDS_PW_CONNECTION               397
#define IDS_PW_DOWNL                    398
#define IDS_PW_UPL                      399
#define IDS_PW_MAXC                     400
#define IDS_PW_CLIENTPORT               401
#define IDS_PW_AUTOCON                  402
#define IDS_PW_RECON                    403
#define IDS_PW_SERVER                   404
#define IDS_PW_RDEAD                    405
#define IDS_PW_RETRIES                  406
#define IDS_PW_SCORE                    407
#define IDS_PW_FILTER                   410
#define IDS_PW_MISC                     412
#define IDS_PW_TRAY                     413
#define IDS_LANMODE                     414
#define IDS_PW_PROMPT                   415
#define IDS_PW_SPLASH                   416
#define IDS_PW_TOOL                     418
#define IDS_PW_FRONT                    419
#define IDS_PW_LANG                     420
#define IDS_PW_FILES                    421
#define IDS_PW_SHARE                    422
#define IDS_PW_EVER                     423
#define IDS_PW_NOONE                    425
#define IDS_PW_RESET                    426
#define IDS_PW_APPLY                    427
#define IDS_EM_TRANS                    428
#define IDS_EM_SEARCH                   430
#define IDS_EM_STATISTIC                433
#define IDS_EM_PREFS                    434
#define IDS_FD_GENERAL                  436
#define IDS_FD_MET                      437
#define IDS_FD_HASH                     438
#define IDS_FD_SIZE                     439
#define IDS_FD_TRANSFER                 440
#define IDS_FD_PARTS                    441
#define IDS_FD_TRANS                    442
#define IDS_FD_DATARATE                 443
#define IDS_FD_COMPSIZE                 444
#define IDS_FD_CLOSE                    445
#define IDS_FD_TITLE                    446
#define IDS_CD_GENERAL                  447
#define IDS_CD_UNAME                    448
#define IDS_CD_UHASH                    449
#define IDS_CD_CSOFT                    450
#define IDS_CD_UIP                      451
#define IDS_CD_SIP                      452
#define IDS_CD_SNAME                    454
#define IDS_CD_CDOWN                    455
#define IDS_CD_DOWN                     456
#define IDS_CD_ADOWN                    457
#define IDS_CD_TDOWN                    458
#define IDS_CD_UP                       459
#define IDS_CD_AUP                      460
#define IDS_CD_TUP                      461
#define IDS_CD_TRANS                    462
#define IDS_CD_SCORES                   463
#define IDS_CD_MOD                      464
#define IDS_CD_RATING                   465
#define IDS_CD_USCORE                   466
#define IDS_CD_TITLE                    467
#define IDS_EMULEW                      468
#define IDS_EMULEW2                     469
#define IDS_EMULEW3                     470
#define IDS_PW_MAXSOURCES               471
#define IDS_SHAREDFILESCOUNT            472
#define IDS_SF_SIZE                     473
#define IDS_ERR_BADPORT                 474
#define IDS_ERR_NOHELLO                 475
#define IDS_ERR_INVALIDPACKAGE          476
#define IDS_ERR_CLIENTERROR             477
#define IDS_ERR_BADSIZE                 478
#define IDS_ERR_NOTAFILELINK            479
#define IDS_ERR_CREATEPARTFILE          480
#define IDS_SCORE                       483
#define IDS_LASTSEEN                    485
#define IDS_BANNED                      486
#define IDS_UUSERS                      487
#define IDS_UFAILED                     488
#define IDS_OPENFILE                    489
#define IDS_DATE                        490
#define IDS_PARTINFOS                   491
#define IDS_PARTINFOS2                  492
#define IDS_USERID                      493
#define IDS_CLIENT                      494
#define IDS_SERVER                      495
#define IDS_SOURCEINFO                  496
#define IDS_CLIENTSOURCENAME            497
#define IDS_USERINFO                    498
#define IDS_FILESTATS_SESSION           499
#define IDS_FILESTATS_TOTAL             500
#define IDS_REQ_UNKNOWNFILE             501
#define IDS_SF_AVERAGESIZE              502
#define IDS_SF_REQUESTS                 503
#define IDS_SF_ACCEPTS                  504
#define IDS_SF_TRANSFERRED              505
#define IDS_REMOVESEARCHSTRING          506
#define IDS_REMOVESELECTED              507
#define IDS_REMOVEALLSEARCH             508
#define IDS_UPLOADTIME                  515
#define IDS_LASTSEENCOMPL               516
#define IDS_YES                         517
#define IDS_NO                          518
#define IDS_UNBAN                       519
#define IDS_ADDTOSTATIC                 521
#define IDS_ADDED2SSF                   522
#define IDS_STATICSERVER                523
#define IDS_ERROR_SSF                   524
#define IDS_SF_ACTIVECON                525
#define IDS_SF_MAXCONLIMITREACHED       526
#define IDS_SF_AVGCON                   527
#define IDS_SF_PEAKCON                  528
#define IDS_NETWORK                     530
#define IDS_QUEUEFULL                   532
#define IDS_AVG                         533
#define IDS_SECS                        539
#define IDS_MINS                        540
#define IDS_HOURS                       541
#define IDS_DAYS                        542
#define IDS_ED2KLINKFIX                 543
#define IDS_RECONNECT                   544
#define IDS_SERVERADDED                 545
#define IDS_STATS_SUCCUPCOUNT           547
#define IDS_STATS_FAILUPCOUNT           549
#define IDS_STATS_AVEUPTIME             550
#define IDS_SEARCHMINSIZE               551
#define IDS_SEARCHMAXSIZE               552
#define IDS_REQ_SHAREDFILES             555
#define IDS_ACCEPTED                    556
#define IDS_DENIED                      557
#define IDS_PW_CON_DOWNLBL              558
#define IDS_PW_CON_UPLBL                559
#define IDS_PW_AUTOCONNECTSTATICONLY    560
#define IDS_PW_CON_LIMITFRM             561
#define IDS_STATS_AVGLABEL              562
#define IDS_GRAPHS                      563
#define IDS_STREE                       564
#define IDS_STATSSETUPINFO              566
#define IDS_HARDLIMIT                   568
#define IDS_TOOMANYCONNS                570
#define IDS_DOWNLOADRENAMED             571
#define IDS_TBN_DOWNLOADDONE            572
#define IDS_PW_CON_CAPFRM               582
#define IDS_DL_TRY_TO_GET_PREVIEW_PARTS 588
#define IDS_IRC_DISCONNECT              594
#define IDS_DOWNLOAD_ALPHABETICAL       598
#define IDB_UP2X                        601
#define IDB_DOWN2X                      603
#define IDS_TAKEOVER                    616
#define IDS_CLEANUP                     617
#define IDS_RENAME                      618
#define IDS_SHARED                      623
#define IDS_DOWNLOADED                  624
#define IDS_SOURCENAMES                 625
#define IDS_PREF_STARTMIN               626
#define IDS_PW_UA                       642
#define IDS_CONNECTIONLOST              645
#define IDS_PW_UNLIMITED                640
#define IDS_HASHINGFILE                 647
#define IDS_REMOVEFROMSTATIC            655
#define IDS_LENGTH                      656
#define IDS_VIDEO                       657
#define IDS_AUDIO                       658
#define IDS_FILEINFO                    659
#define IDS_CODEC                       660
#define IDS_BITRATE                     661
#define IDS_SHAREDFILES_FAILED          667
#define IDS_SHAREDFILES_REQUEST         668
#define IDS_VIEWFILES                   669
//#define IDS_UDPDISABLED                 672
#define IDS_CONCURDWL                   674
#define IDS_STATS_MAXAVGDL              677
#define IDS_STATS_MAXDL                 678
#define IDS_PW_FASTSRVCON               680
#define IDS_ERR_LOADSERVERMET           682
#define IDS_ERR_CORRUPTCOMPRPKG         683
#define IDS_ERR_KNOWNSERVERINFOREC      686
#define IDS_SELECT_INCOMINGDIR          689
#define IDS_SELECT_TEMPDIR              690
#define IDS_PRIOAUTO                    691
#define IDS_PRIOAUTONORMAL              692
#define IDS_PRIOAUTOHIGH                693
#define IDS_PRIOAUTORELEASE             694
#define IDS_PRIOAUTOLOW                 695
#define IDS_ERR_CONTIMEOUT              696
#define IDS_OUTOFSERVERS                697
#define IDS_PW_CONLIMITS                698
#define IDS_MAXCON5SECLABEL             699
#define IDS_PW_UAP                      700
#define IDS_MAXCLIENT                   701
#define IDS_PW_TWEAK                    702
#define IDS_PAF_REQINFO                 705
#define IDS_PAF_MOREINFO                706
#define IDS_ADD                         708
#define IDS_RECOVERED_PARTMET           709
#define IDS_SMARTLOWIDCHECK             730
#define IDS_3DDEP                       732
#define IDS_AUTOTAKEED2KLINKS           733
#define IDS_ADDNEWFILESPAUSED           734
#define IDS_DOWNLOADMOVIECHUNKS         735
#define IDS_OPENPREFINI                 736
#define IDS_STARTNEXTFILE               742
#define IDS_FULLCHUNKTRANS              743
//#define IDS_MANUALSERVERHIGHPRIO        744
#define IDS_VERBOSE                     745
#define IDS_FLAT                        746
#define IDS_ROUND                       747
#define IDS_SAMEUSERHASH                748
#define IDS_SEARCHEXTENTION             749
#define IDS_SEARCHAVAIL                 750
#define IDS_STARTUP                     762
#define IDS_PW_VIDEOPLAYER              770
#define IDS_MYINFO                      772
#define IDS_ID                          773
#define IDS_IDLOW                       774
#define IDS_IDHIGH                      775
#define IDS_TOVERHEAD                   777
#define IDS_FROVERHEAD                  778
#define IDS_SSOVERHEAD                  779
#define IDS_SOVERHEAD                   780
#define IDS_ERR_FILECOMPLETIONTHREAD    781
#define IDS_QUEUESIZE                   783
#define IDS_DAYS2                       784
#define IDS_ERR_MAKEBAKCREDITFILE       785
#define IDS_COMMENT                     786
#define IDS_IPFILTERED                  787
#define IDS_DL_TRANSFCOMPL              788
#define IDS_DL_ACTIVE_TIME              789
#define IDS_STATS_FILTEREDCLIENTS       790
#define IDS_ERR_LARGEREQBLOCK           792
#define IDS_SHOWRATEONTITLE             793
#define IDS_PW_DAP                      795
#define IDS_FD_LASTCHANGE               796
#define IDS_STATS_RUNTIME               797
#define IDS_ALL                         798
#define IDS_CAT_ADD                     799
#define IDS_CAT_EDIT                    800
#define IDS_CAT_REMOVE                  801
#define IDS_CAT                         802
#define IDS_TITLE                       803
#define IDS_COLOR                       804
#define IDS_DEFAULT                     805
#define IDS_PW_DISPLAY                  806
#define IDS_ALLOTHERS                   808
#define IDS_TOCAT                       809
#define IDS_CAT_UNASSIGN                810
#define IDS_ADDDOWNLOADSFROMCB          811
#define IDS_PF_WATCHCB                  812
#define IDS_SECURITY                    813
#define IDS_IPFILTERLOADED              814
#define IDS_IPFILTER                    815
#define IDS_EDIT                        816
#define IDS_FILTERLEVEL                 817
#define IDS_FILTERSERVERBYIPFILTER      818
#define IDS_CLIENTLIST                  820
#define IDS_FOLDER                      821
#define IDS_CL_UPLOADSTATUS             822
#define IDS_CL_TRANSFUP                 823
#define IDS_CL_DOWNLSTATUS              824
#define IDS_CL_TRANSFDOWN               825
#define IDS_CL_PENDING                  826
#define IDS_ERROR                       828
#define IDS_OPENINC                     829
#define IDS_AUTOMATIC                   836
#define IDS_STATIC_CPUMEM               841
#define IDS_KAD_SEARCH_KEYWORD_TOO_SHORT 842
#define IDS_LOG2DISK                    843
#define IDS_KAD_SEARCH_KEYWORD_ALREADY_SEARCHING 844
#define IDS_KAD_SEARCH_KEYWORD_INVALID  845
#define IDS_EDITCAT                     846
#define IDS_ENABLED                     848
#define IDS_SV_DEBUGLOG                 863
#define IDS_WS_PASS                     864
#define IDS_SPEED_LIMITS                869
#define IDS_CAPACITY_LIMITS             870
#define IDS_GLOBALSEARCH                875
#define IDS_METHOD                      876
#define IDS_UNDO                        877
#define IDS_DAYLY                       878
#define IDS_DAY_MO_FR                   879
#define IDS_DAY_SA_SO                   880
#define IDS_MO                          881
#define IDS_DI                          882
#define IDS_MI                          883
#define IDS_DO                          884
#define IDS_FR                          885
#define IDS_SA                          886
#define IDS_SO                          887
#define IDS_DETAILS                     891
#define IDS_ACTION                      892
#define IDS_REMOVE                      893
#define IDS_NEW                         894
#define IDS_ERR_TOOLARGEFILE            896
#define IDS_DAY_MO_SA                   899
#define IDS_LIMITSOURCES                900
#define IDS_LIMITCONS5SEC               901
#define IDS_S_DAYS                      904
#define IDS_STARTTIME                   905
#define IDS_VALUE                       906
#define IDS_SELECTCAT                   910
#define IDS_ALLUNASSIGNED               911
#define IDS_SW_REFETCHRES               914
#define IDS_FILEHASH                    915
#define IDS_PW_PROXY                    916
#define IDS_PROXY_ENABLE                917
#define IDS_PROXY_TYPE                  918
#define IDS_PROXY_HOST                  919
#define IDS_PROXY_PORT                  920
#define IDS_PROXY_AUTH                  921
#define IDS_SHOWCATINFO                 923
#define IDS_COPY                        926
#define IDS_SELECTALL                   927
#define IDS_AUTOSCROLL                  928
#define IDD_INPUTBOX                    933
#define IDS_DL_RESUMENEXT               936
#define IDS_STARTPRIO                   937
#define IDS_PREF_STARTNEXTFILECAT       938
#define IDS_SOFTFILES                   940
#define IDS_HARDFILES                   941
#define IDS_FILTER                      942
#define IDS_DEBUG_SOURCE_EXCHANGE       949
#define IDS_SHAREDREQ1                  950
#define IDS_SHAREDREQ2                  951
#define IDS_SHAREDANSW                  952
#define IDS_SHAREDANSW2                 953
#define IDS_SHAREDINFO1                 954
#define IDS_SHAREDINFO2                 955
#define IDS_SHAREDANSW3                 956
#define IDS_SHAREDREQDENIED             957
#define IDS_AUTOCLEANUPFN               958
#define IDS_ONNEWDOWNLOAD               959
#define IDS_FILTERFILENAMEWORD          960
#define IDS_FNFILTERTITLE               961
#define IDS_CHANGECATVIEW               962
#define IDS_STATS_CUMULATIVE            964
#define IDS_STATS_OVRHD                 965
#define IDS_STATS_RECORDS               966
#define IDS_STATS_COMPDL                967
#define IDS_STATS_SHRECNUM              972
#define IDS_STATS_SHRECSIZE             974
#define IDS_STATS_SHRECASIZE            975
#define IDS_STATS_SESSION               976
#define IDS_STATS_SRATIO                977
#define IDS_STATS_CRATIO                978
#define IDS_STATS_CURRSRVDUR            980
#define IDS_LONGSECS                    981
#define IDS_STATS_DLSES                 982
#define IDS_LONGMINS                    983
#define IDS_STATS_SDLSES                984
#define IDS_STATS_FDLSES                985
#define IDS_STATS_AVGDATADLSES          986
#define IDS_STATS_ULSES                 987
#define IDS_STATS_GAINCOMP              988
#define IDS_STATS_LOSTCORRUPT           989
#define IDS_STATS_AVGDATAULSES          990
#define IDS_STATS_ICHSAVED              991
#define IDS_STATS_MBRESET_TXT           992
#define IDS_STATS_MBRESTORE_TXT         993
#define IDS_ERR_NOSTATBKUP              994
#define IDS_STATS_NFOLOADEDBKUP         995
#define IDS_STATS_NFORESET              996
#define IDS_STATS_BNRESET               997
#define IDS_STATS_BNRESTORE             998
#define IDS_STATS_PROBLEMATIC           1001
#define IDC_SPEED                       1002
#define IDS_LONGHRS                     1002
#define IDS_STATS_LARGESTFILE           1003
#define IDS_SPLIT_WINDOW                1004
#define IDS_STATS_DSPF                  1005
#define IDS_STATS_DATASOURCE            1006
#define IDS_STATS_DSFILE                1007
#define IDS_STATS_GENERAL               1008
#define IDC_DOWNSLD                     1009
#define IDS_STATS_TRANSTIME             1009
#define IDC_DOWNTXT                     1010
#define IDS_STATS_DOWNTIME              1010
#define IDC_UPSLD                       1011
#define IDS_STATS_UPTIME                1011
#define IDC_UPTXT                       1012
#define IDS_STATS_TOTALSRVDUR           1012
#define IDC_SIDEBAR                     1013
#define IDS_STATS_MAXAVGUL              1013
#define IDC_TRAYDOWN                    1014
#define IDS_STATS_MAXUL                 1014
#define IDC_TRAYUP                      1015
#define IDS_STATS_AVGDLTIME             1015
#define IDS_STATS_PRTDEF                1016
#define IDS_STATS_PRTOTHER              1017
#define IDS_STATS_MNUTREECPYSEL         1019
#define IDS_CONDTCPACCEPT               1023
#define IDS_STATS_MNUTREECPYVIS         1024
#define IDS_STATS_MNUTREEEXPANDALL      1025
#define IDS_STATS_MNUTREECOLLAPSEALL    1026
#define IDS_STATS_MNUTREEEXPANDMAIN     1027
#define IDS_STATS_LASTRESETSTATIC       1028
#define IDS_STATS_TIMESTATS             1031
#define IDS_STATS_TIMESINCERESET        1033
#define IDS_CRYPT_INITFAILED            1034
#define IDS_CD_IDENT                    1035
#define IDS_IDENTOK                     1036
#define IDS_IDENTFAILED                 1037
#define IDS_IDENTNOSUPPORT              1038
#define IDS_COMMITFILES                 1039
#define IDS_NEVER                       1041
#define IDS_ALWAYS                      1042
#define IDS_ONSHUTDOWN                  1043
#define IDS_USESECIDENT                 1045
#define IDS_CUT                         1047
#define IDS_STATS_SECUREIDENT           1048
#define IDS_ONDISK                      1049
#define IDS_CLIENTCOL                   1050
#define IDS_SEARCH_UNTERMSTRING         1051
#define IDS_SEARCH_GENERALERROR         1052
#define IDS_SEARCH_MISSINGORRIGHT       1053
#define IDS_SEARCH_MISSINGNOTRIGHT      1054
#define IDS_SEARCH_MISSINGEXPRPARANT    1055
#define IDS_SEARCH_MISSINGCLOSINGPARANT 1056
#define IDS_SEARCH_EXPRERROR            1057
#define IDS_SEARCH_TOOCOMPLEX           1058
#define IDS_VERSION                     1059
#define IDS_OPTIONS                     1060
#define IDS_PASTE                       1061
#define IDS_SEARCHAUTHORCOLLECTION      1062
#define IDS_ERR_DUPL_FILES              1063
#define IDS_A4AF                        1066
#define IDS_ENABLEMM                    1068
#define IDS_AUTOCAT_LABEL               1069
#define IDS_SHOWEXTSETTINGS             1070
#define IDS_TREEOPTIONS_TRUE            1071
#define IDS_TREEOPTIONS_FALSE           1072
#define IDS_TREEOPTIONS_OK              1073
#define IDS_SERVER_LIMITS               1076
#define IDS_KBITSSEC                    1077
#define IDS_KBYTESSEC                   1078
#define IDS_ERR_CREATE_DIR              1079
#define IDS_WRN_INCTEMP_SAME            1082
#define IDS_ARTIST                      1087
#define IDS_ALBUM                       1088
#define IDS_CD_UPLOADREQ                1090
#define IDS_CREDITSEXPIRED              1092
#define IDS_SOURCESINFO                 1093
#define IDS_META_DATA                   1094
#define IDS_TIMEBEFORE                  1095
#define IDS_FD_TIMEDATE                 1096
#define IDS_FILEINFORMATION             1097
#define IDS_COMPLSOURCES                1102
#define IDS_CHECKNOENDTIME              1103
#define IDS_FD_DOWNLOADSTARTED          1104
#define IDS_FAILEDREOPEN                1105
#define IDS_SERVERKEEPALIVETIMEOUT      1116
#define IDS_MORE                        1117
#define IDS_SEARCHPARAMS                1119
#define IDS_HASHINGFILESCOUNT           1120
#define IDS_CHECKDISKSPACE              1121
#define IDS_YOURHOSTNAME                1122
#define IDS_INSUFFICIENT                1123
#define IDS_MINFREEDISKSPACE            1124
#define IDS_WARNING                     1125
#define IDS_ESTTIMELEFT                 1156
#define IDS_TRANSFER_RATE_LABEL         1157
#define IDS_SAVELOG                     1158
#define IDS_DELETESELECTED              1162
#define IDS_ERR_BADFOLDER               1164
//#define IDS_RADCLIENTS                  1168
#define IDS_KADUDPPORTERR               1169
#define IDD_META_DATA                   1170
#define IDS_CONFIRM_FILEDELETE          1170
#define IDS_OPENFOLDER                  1171
#define IDS_RUNASUSER                   1172
#define IDS_DELETE                      1173
#define IDS_BOOTSTRAP                   1174
#define IDS_VIAED2KSQ                   1175
#define IDS_VIAKAD                      1177
#define IDS_VIASE                       1178
#define IDS_MINBITRATE                  1187
//#define IDS_KAD_RECHECKFW               1188
#define IDS_SHAREDTITLE                 1189
#define IDS_FIREWALLED                  1190
#define IDS_KADEMLIA                    1191
#define IDS_KADCONTACTLAB               1192
#define IDS_KAD_UNKNOWN                 1201
#define IDS_SRV_TCPCOMPR                1202
#define IDS_SRV_UDPSR                   1204
#define IDS_SRV_UDPFR                   1205
#define IDS_MINLENGTH                   1206
#define IDS_DYNUP                       1209
#define IDS_KADOVERHEAD                 1210
#define IDS_LOG_BANNED_CLIENTS          1212
#define IDS_LOG_RATING_RECV             1213
#define IDS_LOG_SECURE_IDENT            1214
#define IDS_LOG_FILTERED_IPS            1215
#define IDS_LOG_FILE_SAVING             1216
#define IDS_RAU_WARNING                 1220
#define IDS_ERR_NOTCONNECTEDKAD         1229
#define IDS_KNOWN                       1233
#define IDS_RAU_RUNNING                 1234
#define IDS_RAU_FAILED                  1235
#define IDS_KADCONTACTSREAD             1236
#define IDS_ERR_KADCONTACTS             1237
#define IDS_METATAGS                    1238
#define IDS_UDPREASKS                   1240
#define IDS_LOG_A4AF                    1245
#define IDS_A4AF_SAVE_CPU               1246
#define IDS_SEARCH_DOC                  1247
#define IDS_NEXT_REASK                  1253
#define IDS_A4AF_FILES                  1254
#define IDS_FO_TEMPTCP_S                1255
#define IDS_FO_TEMPTCP_F                1256
#define IDS_FO_TEMPUDP_S                1257
#define IDS_FO_TEMPUDP_F                1258
#define IDS_FO_PREFBUTTON               1259
#define IDS_FO_PREF_SUCCCEEDED          1260
#define IDS_FO_PREF_EXISTED             1261
#define IDS_FO_PREF_FAILED              1262
#define IDS_FO_PREF_STARTUP             1263
#define IDS_LOG_LEVEL                   1264
#define IDS_PREF_STARTNEXTFILECATONLY   1267
#define IDS_LOG_ULDL_EVENTS             1268
#define IDS_SOURCESWAPBLOCKED           1271
#define IDS_TRICKLING                   1272
#define IDS_A4AF_CHECK_THIS_NOW         1273
#define IDS_SEARCH_INVALIDCHAR          1277
#define IDS_STARTTEST                   1280
#define IDS_TESTINFO                    1281
#define IDS_ST_ACTIVEU_ZZ               1288
#define IDS_ST_ULCURRENT                1289
#define IDS_ST_ULSLOTSNOOVERHEAD        1290
#define IDS_STATS_ACTUL_ZZ              1292
#define IDS_STATS_TOTALUL               1293
#define IDS_MAXHALFOPENCONS             1297
#define IDS_KAD_WAITCBK                 1299
#define IDS_KAD_TOOMANDYKADLKPS         1300
#define IDS_PCDS_CLIENTWAIT             1301
#define IDS_PCDS_CACHEWAIT              1302
#define IDS_CACHE                       1303
#define IDS_INDEXED                     1304
#define IDS_KADINFO_SRC                 1305
#define IDS_KADINFO_KEYW                1306
#define IDS_STARTWITHWINDOWS            1307
#define IDS_ADDSRCMANUALLY              1308
#define IDS_BUDDY                       1309
#define IDS_BUDDYNONE                   1310
#define IDS_HALF                        1312
#define IDS_CONCOMPL                    1313
#define IDS_FORMAT                      1316
#define IDS_META_COLLECTION             1317
#define IDS_META_PARTPATH               1318
#define IDS_META_PARTHASH               1319
#define IDS_META_GAPSTART               1320
#define IDS_META_GAPEND                 1321
#define IDS_FAIL                        1322
#define IDS_META_PREFERENCES            1323
#define IDS_META_VERSION                1324
#define IDS_META_TEMPFILE               1325
#define IDS_META_SERVERPORT             1326
#define IDS_META_SERVERIP               1327
#define IDS_META_SRCUDPPORT             1328
#define IDS_META_SRCTCPPORT             1329
#define IDS_META_SRCIP                  1330
#define IDS_META_SRCTYPE                1331
#define IDS_PF_ADVANCEDCALC             1333
#define IDS_LD_ED2KLINK                 1334
#define IDS_LD_COPYCLIPBOARD            1335
#define IDS_LD_HOSTNAME                 1336
#define IDS_SAVEACFAILED                1337
#define IDS_AICHHASH                    1338
#define IDS_STATS_MINORCLIENTS          1344
#define IDS_AICH_SYNCTOTAL              1345
#define IDS_AICH_CALCFILE               1346
#define IDD_DIRECT_DOWNLOAD             1347
#define IDS_AICH_WARNUSER               1347
#define IDD_SEARCH_PARAMS               1348
#define IDS_AICH_WORKED                 1348
#define IDS_USERSIP                     1350
#define IDS_FEATURES                    1351
#define IDS_SPARSEPARTFILES             1354
#define IDS_NEGATEFILTER                1356
#define IDS_SEENCOMPL                   1357
#define IDS_ASKDLINCOMPLETE             1359
#define IDS_DEADSOURCES                 1360
#define IDR_WIDECHARLOWERMAP            1362
#define IDS_SHORTTAGS                   1363
#define IDS_THELOAD                     1364
#define IDD_ADDSOURCE                   1365
#define IDS_COMCTRL32_DLL_TOOOLD        1370
#define IDS_ASREGEXPR                   1371
#define IDS_STATIC_REGEXP               1372
#define IDS_CARE4ALL                    1373
#define IDS_REGEXPRESSION               1374
#define IDS_DWL_IPFILTERFILE            1376
#define IDS_DWLIPFILTERFAILED           1377
#define IDS_ERR_IPFILTERZIPEXTR         1379
#define IDS_ERR_IPFILTERCONTENTERR      1380
#define IDS_SETPFSLIMIT                 1395
#define IDS_SETPFSLIMITEXPLAINED        1396
#define IDS_UPDATECATINCOMINGDIRS       1397
#define IDS_ERR_FAILEDTOLOAD            1399
#define IDS_TCPIP_CONNS                 1400
#define IDS_MANUAL_FILENAMECLEANUP      1401
#define IDS_ERR_DELFILE                 1402
#define IDS_ERR_CONFIGCORRUPT           1403
#define IDS_UPLOADING                   1404
#define IDS_CANCELLED                   1405
#define IDS_PW_REMEMBERDOWNLOADED       1406
#define IDS_PW_REMEMBERCANCELLED        1407
#define IDS_PW_SHOWTRANSTOOLBAR         1416
#define IDS_SEARCH_EMULECOLLECTION      1418
#define IDS_COLLECTIONLIST              1422
//#define IDS_SEARCHRELATED               1429
//#define IDS_RELATED                     1430
#define IDS_AUTHOR                      1436
#define IDS_AUTHORKEY                   1437
#define IDS_COLL_ADDINCAT               1438
#define IDS_VIEWCOLLECTION              1439
#define IDS_RUNNINGRESTRICTED           1441
#define IDS_SHAREWARNING                1446
#define IDS_REMOVEALLSERVERS            1447
#define IDS_SEARCH_UNKATTR              1448
#define IDS_SEARCH_ATTRERR              1449
#define IDS_SEARCH_MISSINGANDRIGHT      1450
#define IDS_SEARCH_OPRERR               1451
#define IDS_DOWNLOADING_SERVERMET_FROM  1453
#define IDS_DOWNLOADING_SERVERMET       1454
#define IDS_FULLALLOC                   1455
#define IDS_CONVERTINGKNOWN2MET         1461
#define IDS_CONVERTINGKNOWN2FAILED      1462
#define IDS_CONVERTINGKNOWN2DONE        1463
#define IDS_ERR_MET_BAD                 1464
#define IDS_SRV_LARGEFILES              1465
#define IDS_ERR_FSCANTHANDLEFILE        1466
#define IDS_RESTORESEARCHPARAMS         1472
#define IDR_LISTVIEW                    1481
#define IDS_OBFUSCATION                 1490
#define IDS_SUPPORTED                   1491
#define IDS_PROTOCOLOBFUSCATION         1501
#define IDS_ONLYOBFUSCATED              1502
#define IDS_DISABLEOBFUSCATION          1503
#define IDS_ENABLEOBFUSCATION           1504
#define IDS_CONNECTINGTOOBFUSCATED      1505
#define IDS_CONNECTEDTOOBFUSCATED       1506
#define IDS_OBFUSCATED                  1508
#define IDS_UNVERIFIED                  1509
#define IDS_US_STALLEDW4BR              1514
#define IDS_US_STALLEDREADINGFDISK      1515
#define IDS_SERVERFEATURE_INTTYPETAGS   1516
#define IDS_FILLGRAPHS                  1517
#define IDS_PARAMETER                   1518
#define IDS_UPNPSTART                   1520
#define IDS_UPNPSETUP                   1521
#define IDS_UPNPFAILED                  1522
#define IDS_UPNPSUCCESS                 1523
#define IDS_FO_PREFBUTTON_NEW           1524
#define IDS_UPNP_NOSERVICE              1525
#define IDS_DELAYEDBYUPNP               1526
#define IDS_DELAYEDBYUPNP2              1527
#define IDS_UPNP                        1528
#define IDS_UPNPCLOSEONEXIT             1529
#define IDS_UPNPSKIPWANIP               1530
#define IDS_UPNPSKIPWANPPP              1531
#define IDS_SHAREEMULELABEL             1532
#define IDS_SHAREEMULEMULTI             1533
#define IDS_SHAREEMULEPUBLIC            1534
#define IDS_SHAREEMULEOLD               1535
#define IDS_SHAREEMULEWARNING           1536
#define IDS_SPAM                        1537
#define IDS_MARKSPAM                    1538
#define IDS_MARKNOTSPAM                 1539
#define IDS_SEARCHSPAMFILTER            1540
#define IDS_DOWNLOADING_NODESDAT_FROM   1547
#define IDS_DOWNLOADING_NODESDAT        1548
#define IDS_ERR_FAILEDDOWNLOADNODES     1549
#define IDS_PREVENTSTANDBY              1550
#define IDS_KADID                       1551
#define IDS_SEARCHINGFRIENDKAD          1552
#define IDS_FOUND                       1553
#define IDS_EXTERNUDPPORT               1554
#define IDS_STORESEARCHES               1555
#define IDS_WRN_INCFILE_EXISTS          1556
#define IDS_CONFIRMNODESDOWNLOAD        1561
#define IDS_ERR_SHARED_DIR              1563
#define IDS_CHECK_FILE_OPEN             1565
#define IDS_UNSHARE                     1568
#define IDS_ADDEDON                     1570
#define IDS_RESOLVELINKS                1571
#define IDS_PAUSEONPREVIEW              1572
#define IDS_PREVIEWWITH                 1573
#define IDS_SEARCH_BADOPERATORCOMBINATION 1577
#define IDS_CLOSEEMULE                  1587
#define IDS_DONOTASKAGAIN               1588
#define IDC_STATUS                      2001
#define IDC_FILESTATUS                  2002
#define IDC_TIMELEFT                    2003
#define IDC_TRANSFER_RATE               2004
#define IDC_MAXSOURCEPERFILE            2005
#define IDC_TITLEWINDOW                 2006
#define IDC_ELINK                       2010
#define IDC_LOGBOX                      2013
#define IDC_VIDEOPLAYER                 2020
#define IDC_MAXCON                      2023
//#define IDC_RUMAXDOWN                   2025
#define IDC_REFRESH_BUTTON				2026
#define IDC_BROWSEV                     2027
#define IDC_REMOVE                      2028
#define IDC_INCFILES                    2035
#define IDC_UPLOADLIST                  2036
#define IDD_RESUME_DOWNLOAD             2039
#define IDC_MYINFOLIST                  2041
#define IDC_TAGS                        2042
#define IDC_PARTSTATUS                  2046
#define IDC_DOWNLOADLIST                2048
#define IDC_CLEARALL                    2053
#define IDC_SELINCDIR                   2054
#define IDC_TAKEOVER                    2055
#define IDC_ADD                         2058
#define IDC_BROWSE                      2061
#define IDC_RELOADFILTER                2062
#define IDC_HOTMENU                     2063
#define IDC_LOADURL                     2063
//#define IDC_BOOTSTRAPBUTTON             2065
#define IDC_PV_EXIT                     2066
#define IDC_DEBUG_OPTS                  2067
#define IDC_SEARCH_RESET                2076
#define IDC_PV_NEXT                     2078
#define IDC_PV_PRIOR                    2084
#define IDC_SERVLIST_TEXT               2085
#define IDC_SERVLIST                    2091
#define IDC_CANCELS                     2093
#define IDC_STATTREE                    2094
#define IDC_EXT_OPTS                    2095
#define IDC_SERVERRETRIES               2105
#define IDC_SHOWCATINFO                 2110
//#define IDC_NETWORK_KADEMLIA            2114
#define IDC_SHOWRATEONTITLE             2123
#define IDC_S_ENABLE                    2126
#define IDC_SCORE                       2128
#define IDC_FULLCHUNKTRANS              2131
#define IDC_USESECIDENT                 2134
//#define IDC_REFUSEUPLOAD                2134
#define IDC_RUNASUSER                   2135
#define IDC_RANDOMPORTONSTARTUP         2135
#define IDC_ENABLEOBFUSCATION           2136
#define IDC_ONLYOBFUSCATED              2137
#define IDC_DISABLEOBFUSCATION          2139
#define IDC_SEARCHSPAMFILTER            2140
#define IDC_TEMPLIST                    2156
#define IDC_PORT                        2162
#define IDC_APPLY                       2164
#define IDC_UPLOAD_CAP                  2166
#define IDC_SFLIST                      2167
//#define IDC_ADDSERVER                   2169
#define IDC_DOWNLOAD_CAP                2171
#define IDC_SEARCHLIST                  2172
//#define IDC_UPDATENODESDATFROMURL       2173
//#define IDC_UPDATESERVERMETFROMURL      2174
#define IDC_COMBO1                      2175
#define IDC_PROGRESS1                   2180
#define IDC_SEARCHNAME                  2183
//#define IDC_AUTOCONNECT                 2185
#define IDC_STARTS                      2189
#define IDC_SHOWTRANSTOOLBAR            2189
#define IDC_STORESEARCHES               2190
#define IDC_QUEUECOUNT                  2192
#define IDC_TOTALBUFFER                 2193
#define IDC_MORE                        2196
#define IDC_FLAT                        2197
//#define IDC_SSTATIC4                    2210
//#define IDC_SSTATIC7                    2215
#define IDC_FSTATIC2                    2217
#define IDC_MYINFO                      2219
#define IDC_MSTATIC3                    2221
#define IDC_DSOFT                       2229
#define IDC_DSIP                        2235
#define IDC_DHASH                       2237
#define IDC_DID                         2241
#define IDC_DSNAME                      2243
#define IDC_DDOWNLOADING                2245
#define IDC_DDOWN                       2247
#define IDC_DAVDR                       2248
#define IDC_DDUP                        2249
#define IDC_DAVUR                       2250
#define IDC_DDOWNTOTAL                  2251
#define IDC_DUPTOTAL                    2252
#define IDC_DRATIO                      2253
#define IDC_UPLOADING                   2254
#define IDC_DRATING                     2255
#define IDC_DSCORE                      2256
#define IDC_POPBAR                      2262
#define IDC_POPBAR2                     2265
#define IDC_SHARELIST                   2266
#define IDC_POPBAR3                     2268
#define IDC_SCOPE_D                     2270
#define IDC_SLIDER                      2276
#define IDD_STATISTICS                  2296
#define IDD_SPEEDGRAPH                  2301
#define IDC_SCOPE_U                     2305
#define IDC_EXIT                        2311
#define IDC_SPLASHON                    2315
#define IDC_TYPESEARCH                  2322
#define IDC_FILTER                      2327
//#define IDC_UDPDISABLE                  2330
#define IDC_PREVIEWPRIO                 2332
#define IDC_FNAME                       2335
#define IDC_METFILE                     2337
#define IDC_ADDNEWFILESPAUSED           2338
#define IDC_FHASH                       2339
#define IDC_FSIZE                       2340
#define IDC_SAFESERVERCONNECT           2341
#define IDC_FD_AICHHASH                 2341
#define IDC_PFSTATUS                    2343
#define IDC_PARTCOUNT                   2344
#define IDC_TRANSFERRED                 2345
#define IDC_COMPLSIZE                   2346
#define IDC_DATARATE                    2348
#define IDC_SOURCECOUNT                 2349
#define IDC_SPLITTER                    2351
#define IDC_LASTSEENCOMPL               2355
#define IDC_STARTMIN                    2356
#define IDC_FILECREATED                 2357
#define IDC_LASTRECEIVED                2358
#define IDC_LANGS                       2359
#define IDC_DL_ACTIVE_TIME              2359
#define IDC_NETWORK_ED2K                2363
#define IDC_BRINGTOFOREGROUND           2365
#define IDC_AUTOCONNECTSTATICONLY       2367
#define IDC_STARTNEXTFILE               2368
#define IDC_DISABLEHISTORYLIST          2369
#define IDC_REMEMBERDOWNLOADED          2369
#define IDC_REMOVEDEAD                  2370
#define IDC_REMEMBERCANCELLED           2370
#define IDC_DOWNHISTORYLIST             2371
#define IDC_LISTCTRLFILENAMES           2373
#define IDC_S_TITLE                     2374
#define IDC_UDPPORTLABEL                2376
//#define IDC_RUKBS                       2378
#define IDC_LANG_FRM                    2379
#define IDC_FD_X0                       2381
#define IDC_FD_X1                       2382
#define IDC_FD_X5                       2383
#define IDC_FD_X6                       2384
#define IDC_FD_X7                       2385
#define IDC_FD_X8                       2386
#define IDC_FD_X9                       2387
#define IDC_STATIC30                    2388
#define IDC_FD_X10                      2388
#define IDC_FD_X11                      2389
#define IDC_STATIC31                    2390
#define IDC_STATIC32                    2392
#define IDC_FD_X12                      2393
#define IDC_STATIC33                    2394
#define IDC_FD_X13                      2395
#define IDC_STATIC34                    2396
#define IDC_FD_X14                      2397
#define IDC_STATIC35                    2398
#define IDC_FD_X15                      2400
#define IDC_STATIC38                    2402
#define IDC_FD_LASTCHANGE               2403
#define IDC_STATIC40                    2404
#define IDC_FD_X16                      2405
#define IDC_STATIC41                    2406
#define IDC_STATIC42                    2407
#define IDC_STATIC43                    2408
#define IDC_STATIC44                    2409
#define IDC_STATIC45                    2410
#define IDC_STATIC46                    2411
#define IDC_STATIC47                    2412
#define IDC_STATIC50                    2413
#define IDC_STATIC51                    2414
#define IDC_STATIC52                    2415
#define IDC_STATIC53                    2416
#define IDC_STATIC48                    2419
#define IDC_MSTATIC7                    2429
//#define IDC_FIREWALLCHECKBUTTON         2436
#define IDC_ED2KFIX                     2437
//#define IDC_KADCONNECT                  2440
#define IDC_LOGRESET                    2441
#define IDC_TAB1                        2442
#define IDC_SEARCHLST_ICO               2448
#define IDC_SERVLST_ICO                 2449
#define IDC_PREVENTSTANDBY              2449
#define IDC_BALLONOTIFIER				2450
#define IDC_DOWNLOAD_ICO                2452
#define IDC_METH                        2456
#define IDC_UPLOAD_ICO                  2457
#define IDC_SLIDERINFO                  2463
#define IDC_SLIDERINFO2                 2464
#define IDC_SLIDER2                     2465
#define IDC_SLIDER3                     2466
#define IDC_CAPACITIES_FRM              2476
#define IDC_LIMITS_FRM                  2477
#define IDC_DCAP_LBL                    2478
#define IDC_UCAP_LBL                    2479
#define IDC_DLIMIT_LBL                  2480
#define IDC_ULIMIT_LBL                  2481
#define IDC_CLIENTPORT_FRM              2482
#define IDC_MAXCONN_FRM                 2483
#define IDC_MAXSRC_FRM                  2484
#define IDC_MAXSRCHARD_LBL              2485
#define IDC_MISC_FRM                    2488
#define IDC_RETRIES_LBL                 2490
#define IDC_INCOMING_FRM                2491
#define IDC_SLIDERINFO3                 2499
#define IDC_GRAPHS                      2502
#define IDC_STREE                       2505
#define IDD_PPG_TWEAKS                  2507
#define IDC_KBS1                        2508
#define IDC_KBS2                        2510
#define IDC_KBS3                        2512
#define IDC_KBS4                        2513
#define IDD_PPG_DEBUG                   2514
#define IDC_FILENAME                    2528
#define IDC_FD_SN                       2530
#define IDC_UDPPORT                     2536
#define IDC_USERNAME                    2537
#define IDC_DEBUG_LOG                   2541
#define IDC_TITLE                       2542
#define IDC_FILTERLEVEL                 2543
#define IDC_TEXT                        2544
//#define IDC_BOOTSTRAPIP                 2547
#define IDC_USERHASH                    2549
#define IDC_INCOMING                    2550
#define IDC_AFKADID                     2550
#define IDC_IP                          2553
#define IDC_COMMENT                     2554
#define IDC_AUTOCATEXT                  2558
#define IDC_REGEXP                      2559
#define IDC_KBITS                       2579
#define IDC_KBYTES                      2580
#define IDC_MAXCONLABEL                 2584
#define IDC_WARNING                     2586
#define IDC_INFO1                       2588
#define IDC_INFO2                       2589
#define IDC_TAB3                        2599
#define IDC_3DDEPTH                     2600
#define IDC_3DDEP                       2601
//#define IDC_MANUALSERVERHIGHPRIO        2602
#define IDC_ROUND                       2605
#define IDC_STARTUP                     2606
#define IDC_STATICVIDEOPLAYER           2607
#define IDC_GLOBALBUFFERSIZE_STATIC     2609
#define IDC_GLOBALBUFFERSIZE            2610
#define IDC_QUEUESIZE_STATIC            2611
#define IDC_QUEUESIZE                   2612
#define IDC_DAP                         2616
#define IDC_FNCLEANUP                   2617
#define IDC_DLTAB                       2618
#define IDC_STATIC_INCOMING             2619
#define IDC_STATIC_TITLE                2620
#define IDC_STATIC_COMMENT              2621
#define IDC_STATIC_DLTOof               2622
#define IDC_STATIC_TEMP                 2622
#define IDC_STATIC_AUTOCAT              2623
#define IDC_STATIC_REGEXP               2624
#define IDC_FILTERSERVERBYIPFILTER      2626
#define IDC_STATIC_FILTERLEVEL          2627
#define IDC_STATIC_IPFILTER             2628
#define IDC_STATIC_UPDATEFROM           2630
#define IDC_STATIC_FILTERLEVEL2         2631
#define IDC_EDITFILTER                  2632
#define IDC_CATCOLOR                    2633
#define IDC_WATCHCB                     2635
#define IDC_STATIC_COLOR                2636
#define IDC_PF_TIMECALC                 2636
#define IDC_CATTAB2                     2637
#define IDC_STATIC_CPUMEM               2639
#define IDC_IBLABEL                     2642
#define IDC_DATETIMEPICKER1             2652
#define IDC_STATIC_S_TITLE              2654
#define IDC_STATIC_S_TIME               2655
#define IDC_STATIC_S_ACTION             2656
#define IDC_DATETIMEPICKER2             2657
#define IDC_TIMESEL                     2658
#define IDC_STATIC_DETAILS              2659
#define IDC_NEW                         2660
#define IDC_RECONN                      2662
#define IDC_UAP                         2665
#define IDC_SMARTIDCHECK                2666
#define IDC_ENABLE                      2672
#define IDC_WSUPNP                      2672
#define IDC_TEMPREM                     2673
#define IDC_SHAREADD                    2674
#define IDC_SHAREREM                    2675
#define IDC_FD_X2                       2676
#define IDC_TEMPADD                     2676
#define IDC_FD_X3                       2677
#define IDC_SHAREADDALL                 2677
#define IDC_FD_X4                       2678
#define IDC_FD_XAICH                    2679
#define IDC_EDIT2                       2681
#define IDD_PPG_PROXY                   2684
#define IDC_ENABLEPROXY                 2685
#define IDC_ENABLEAUTH                  2686
#define IDC_PROXYTYPE                   2687
#define IDC_PROXYNAME                   2688
#define IDC_PROXYPORT                   2689
#define IDC_USERNAME_A                  2690
#define IDC_PASSWORD                    2691
#define IDC_PROXYTYPE_LBL               2692
#define IDC_PROXYNAME_LBL               2693
#define IDC_PROXYPORT_LBL               2694
#define IDC_USERNAME_LBL                2695
#define IDC_PASSWORD_LBL                2696
#define IDC_AUTH_LBL                    2697
#define IDD_PPG_DISPLAY                 2707
#define IDD_CAT                         2708
#define IDD_PPG_SECURITY                2710
#define IDC_STATIC_PRIO                 2712
#define IDC_PRIOCOMBO                   2713
#define IDC_TEMPCOMBO                   2714
#define IDC_STARTNEXTFILECAT            2716
#define IDC_STARTNEXTFILECAT2           2718
#define IDC_LAST_SEEN_LABEL             2727
#define IDC_ONND                        2728
#define IDC_FNC                         2729
#define IDC_STATIC_LASTRESET            2736
#define IDC_STATIC133x                  2743
#define IDC_CDIDENT                     2744
#define IDC_UNCADD                      2745
#define IDC_SEC_MISC                    2747
#define IDC_SEC_OBFUSCATIONBOX          2748
//#define IDC_BOOTSTRAPPORT               2760
#define IDC_PV_IMAGE                    2761
//#define IDC_CONNECTION_NETWORK          2762
#define IDC_CLEANFILENAME               2765
//#define IDC_BSSTATIC                    2766
#define IDD_FILEDETAILS_INFO            2767
#define IDC_BUTTONSTRIP                 2769
#define IDD_FILEDETAILS_NAME            2770
#define IDC_CHECKNOENDTIME              2771
#define IDC_TOTAL_TAGS                  2772
#define IDC_MAXUP_SLIDER                2774
#define IDC_MAXDOWN_SLIDER              2775
#define IDC_PREVIEW_INFO                2777
#define IDC_HASHSET                     2779
#define IDC_RECOVERED                   2781
#define IDC_CORRUPTED                   2786
#define IDC_COMPRESSION                 2787
#define IDD_ED2KLINK                    2787
#define IDC_TIMELEFTTEXT                2789
#define IDC_TRANSFER_RATE_LABEL         2790
//#define IDC_RADIP                       2791
//#define IDC_RADCLIENTS                  2792
#define IDC_HSAV                        2793
#define IDC_FD_CORR                     2794
#define IDC_FD_RECOV                    2795
#define IDC_FD_COMPR                    2796
#define IDC_UPDATEURL                   2797
#define IDC_REMAINING                   2798
#define IDC_DD                          2799
#define IDC_REMAINING_TEXT              2800
#define IDC_TRAY_EXIT                   2802
#define IDC_DOWNKB                      2803
#define IDC_UPKB                        2804
#define IDC_DOWNLBL                     2805
#define IDC_UPLBL                       2806
#define IDC_DL_ACTIVE_TIME_LBL          2820
#define IDC_SEARCH_OPTS                 2833
#define IDC_OPEN_PARAMS_WND             2835
#define IDC_PREVIEW                     2837
#define IDC_CATLABEL                    2840
#define IDC_CATS                        2841
#define IDC_OPENPORTS                   2844
#define IDC_STARTTEST                   2853
#define IDC_SPLITTER_STAT               2859
#define IDC_SPLITTER_STAT_HR            2860
#define IDC_CLIENTDETAIL_KAD            2876
#define IDC_LD_LINKEDI                  2877
#define IDC_CLIENTDETAIL_KADCON         2878
#define IDC_STARTWIN                    2882
#define IDC_EDIT3                       2887
#define IDC_BUTTON1                     2899
#define IDC_LD_LINKGROUP                2900
#define IDC_LD_BASICGROUP               2901
#define IDC_LD_ADVANCEDGROUP            2902
#define IDC_LD_CLIPBOARDBUT             2903
#define IDC_LD_SOURCECHE                2904
#define IDC_LD_HASHSETCHE               2906
#define IDC_LD_HOSTNAMECHE              2909
#define IDC_UIP                         2910
#define IDC_REGEXPR                     2912
#define IDC_DOWNLOADCLIENTS             2918
#define IDD_COLLECTIONVIEWDIALOG        2924
#define IDC_COLLECTIONVIEWCATEGORYCHECK 2925
#define IDC_COLLECTIONVEWLIST           2928
#define IDC_COLLECTIONVIEWLISTLABEL     2930
#define IDC_COLLECTIONVIEWLISTICON      2931
#define IDC_VIEWCOLLECTIONDL            2933
#define IDC_COLLECTIONVIEWAUTHORLABEL   2935
#define IDC_COLLECTIONVIEWAUTHOR        2936
#define IDC_COLLECTIONVIEWAUTHORKEYLABEL 2937
#define IDC_COLLECTIONVIEWAUTHORKEY     2939
#define IDC_SPLITTER_SERVER             2943
#define IDC_SPLITTER_SHAREDFILES        2944
#define IDC_VCOLL_DETAILS               2945
#define IDC_VCOLL_OPTIONS               2946
#define IDC_VCOLL_CLOSE                 2947
#define IDC_COLOUR                      2953
#define IDC_UNDERLINE                   2954
#define IDC_BOLD                        2955
#define IDC_FILELIST                    2965
#define IDC_STATIC_OBF_LABEL            2976
#define IDC_OBFUSCATION_STAT            2977
#define IDC_FILL_GRAPHS                 2983
#define IDC_LBL_MISC                    2986
#define IDC_UPNPSTART                   2987
#define IDC_UPNPPROGRESS                2988
#define IDC_UPNPSTATUS                  2989
#define IDC_PREF_UPNPONSTART            2990
#define IDC_AFKADIDLABEL                2993
#define IDC_SHAREDFILES_FILTER          2994
#define IDC_CHECK_FILE_OPEN             2998
#define IDC_OPENPREFINI                 3012
// ==========  Xtreme Mod  ==========
#define IDS_DROPNONEEDEDSRCS            4000
#define IDS_DROPQUEUEFULLSRCS           4001
#define IDS_STOP_CLIENT                 4006
#define IDS_SubMenu_Drop                4007
#define IDS_PPG_MAELLA_NAFC_CHECK02     4011
#define IDS_LOGDROP                     4018
#define IDS_POWERRELEASE                4022
#define IDS_DONTREMOVESTATICSERVER      4023
#define IDS_REMEMBERAICH                4053
#define IDS_MARKCANCELLED               4054
#define IDS_DOWNHISTORY_CHECK1          4055
#define IDS_DOWNHISTORY_CHECK2          4056
#define IDS_DOWNHISTORY_CHECK3          4057
#define IDS_DOWNHISTORY_CHECK4          4058
#define IDS_DOWNHISTORY                 4059
#define IDS_DOWNHISTORY_REMOVE          4060
#define IDS_DOWNHISTORY_REMOVE_QUESTION 4061
#define IDS_DOWNHISTORY_REMOVE_QUESTION_MULTIPLE 4062
#define IDS_DOWNHISTORY_SHARED          4063
#define IDS_DOWNHISTORY_CLEAR           4064
#define IDS_DOWNHISTORY_SHOWSHARED      4066
#define IDS_DOWNHISTORY_CLEAR_QUESTION  4068
#define IDS_SENDBUFFER                  4069
#define IDS_ALL_A4AF_TO_THIS            4072
#define IDS_ALL_A4AF_TO_OTHER           4073
#define IDS_SWAP_A4AF_TO_THIS           4074
#define IDS_SWAP_A4AF_TO_OTHER          4075
#define IDS_ALL_A4AF_AUTO               4076
#define IDS_UPDOWNUPLOADLIST            4114
#define IDS_UPLOADSLOTSPEED_LABEL       4123
#define IDS_AUTOUPDATEIPFILTER          4127
#define IDS_LOGPARTMISMATCH             4129
#define IDS_CN_UPNPTRYRANDOM            4130
#define IDS_UPLOADINSTABLE              4133
#define IDS_STATIC_DOWNINFO             4150
#define IDS_UPNPSTATUS                  4154
#define IDS_UPNPSTATUS_OK               4155
#define IDS_UPNPSTATUS_NOTINLAN         4156
#define IDS_UPNPSTATUS_ERROR            4157
#define IDS_UPNPSTATUS_PORTINUSE        4158
#define IDS_UPNPSTATUS_PORTINUSE2       4159
#define IDS_UPNP_REBINDTEXT             4160
#define IDS_OBFUSCATION_PADDING_LENGTH  4174
#define IDS_PROGRESSHASHDONE            4184
#define IDS_ENABLEKNOWN2BUFFER		    4188
//zz_fly :: End
#define IDC_UPREDUCTION                 5002
#define IDC_NAFCFULLCONTROL             5004
#define IDC_MAXDOWN                     5005
#define IDC_MAXUP                       5006
#define IDC_DONTREMOVESTATICSERVER      5019
#define IDC_DLOC                        5024
#define IDC_DCAP_LBL2                   5027
#define IDC_UCAP_LBL2                   5028
#define IDC_UCAP_LBL3                   5029
#define IDC_SLOTSPEED_LBL               5030
#define IDC_REMEMBERAICH                5031
#define IDC_DOWNQUEUERANK               5072
#define IDC_UPLOADQUEURANK              5073
#define IDC_AUTOUPDATEIPFILTER          5084
#define IDC_STATIC_DOWNINFO             5089
#define IDS_EMULE_CTRL_DATA             5107
#define IDS_NETWORK_ADAPTER             5108
// ==========  X Mod Strings ==========
//#define IDC_ACTIVEDOWNLOADSRED          8067
#define IDC_DONTCOMPRESSEXT_LBL         8032
#define IDC_DONTCOMPRESSEXT             8033
#define IDC_PAUSEONCOMP                 8034
#define IDC_DONTSHAREXT_LBL             8035
#define IDC_DONTSHAREXT                 8036
#define IDC_QUERYONHASHING_STATIC       8037
#define IDC_DEFAULT_RADIO               8038
#define IDC_NOHASHING_RADIO             8039
#define IDC_QUERY_RADIO			        8040
#define IDS_UL_SPEED                    8085
//#define IDC_KADFRAME                    8119
#define IDC_STATIC_UPQUEUERANK          8131
#define IDC_STATIC_DOWNQUEUERANK        8132
#define IDS_CONFIRMSERVERDOWNLOAD       8136
//#define IDS_PW_REFUSEUPLOAD             8202
#define IDS_DONTCOMPRESSEXT             8205
#define IDS_PAUSEONCOMP                 8206
#define IDS_INVMODE                     8219
#define IDS_INVMODE_MODKEY              8220
#define IDS_INVMODE_VKEY                8221
#define IDS_INVMODE_START               8223
#define IDS_CLEAR0KCLIENT               8224
#define IDS_TRY2FLUSH                   8225
#define IDS_PREALLDISCSPACE             8226
#define IDS_FV_SIZELARGE                8227
#define IDS_FV_SIZESMALL                8228
#define IDS_FV_SIZENA                   8229
#define IDS_MNUFILE                     8231
#define IDS_MNUTOOLBAR                  8232
#define IDS_MNUVIEW                     8233
#define IDS_DISABLEHISTORYLIST          8234
#define IDS_READONLY                    8235
#define IDS_DONTSHAREXT                 8240
#define IDS_ACTIONBE4ASHING             8241
#define IDS_NOHASHING                   8242
#define IDS_QUERY                       8243
#define IDS_QUERYONHASHING              8244
#define IDS_QUERYONHASHING2             8245
#define IDS_SW_RESUMEDOWNLOAD           8246
#define IDS_SHOWSHAREABLE				8251
#define IDS_SW_REMOVEALLBANNEDCLIENTS	8252
#define IDS_SLS							8253
#define IDS_TOGGLESPEEDGRAPH			8254
#define IDS_RANDOMPORTONSTARTUP			8255
#define IDS_GLOBALBUFFERSIZE			8256
#define IDS_PW_BALLONOTIFIER			8257
#define IDS_TOOLS						8258
#define IDS_MNUCATTABBAR				8259
#define IDS_SELECT_SHAREDIR				8260
#define IDS_SELECT_SHAREDIR_SUB			8261
#define IDS_ABORT						8263
#define IDS_CONTINUE					8264
#define IDS_DONOTTELLAGAIN				8265
#define IDS_DONOTSHOWAGAIN				8266
#define IDS_IGNORE						8267
#define IDS_IGNOREALL					8268
#define IDS_NOTOALL						8269
#define IDS_RETRY						8271
#define IDS_SKIP						8272
#define IDS_SKIPALL						8273
#define IDS_TRYAGAIN					8274
#define IDS_MB_YES						8275
#define IDS_YESTOALL					8276
// ==> Pay Back First
#define IDS_STATS_PBFRATIO              9000
#define IDS_STATS_UDATA_PBF             9001
#define IDS_PBFDETAIL                   9002
#define IDC_PBF_CHECK                   9003
// <== Pay Back First
#define IDS_UPDOWN_NEW                  9004
#define IDS_UPDOWNSMALL_NEW             9005
#define IDS_STATUS_TIP                  9006
#define IDS_STATUS_TIP_2                9007
#define IDS_STATUS_TIP_3                9008
#define IDS_STATUS_TIP_4                9009
#define IDC_SHOW_BUFFER_DISPLAY         9010
#define IDS_SHOW_BUFFER_DISPLAY         9011
#define	IDS_RESTARTEMULEONCHANGE		9012
#define IDC_ASSIGNED2K                  9013
#define IDS_SHELLCONTEXT                9014 // ShellContextMenu
// ==> Spread bars [Slugfiller/MorphXT] - Stulle
#define IDS_SF_UPLOADED_PARTS           9015
#define IDS_SPREAD_RESET                9016
// <== Spread bars [Slugfiller/MorphXT] - Stulle

#define IDA_ENTER                       32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4195
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         5107
#define _APS_NEXT_SYMED_VALUE           1591
#endif
#endif
